### ISSUE TITLE
std::queue is not thread-safe

### ISSUE THREAD

**Issue by Meachamp** [timschumi/gmod-chttp#10]
You should either be wrapping it in a lock or moving to a queue that is thread safe. C++ does not guarantee thread safety for this class, and even if it looks like there are no ways for something to happen, something _will_.

See these stackoverflow ansers:
https://stackoverflow.com/questions/34307546/stl-container-for-a-single-produceer-single-consumer-fifo
https://stackoverflow.com/questions/36762248/why-is-stdqueue-not-thread-safe/36763257

**Comment by timschumi** [comment]
Huh, I thought I had found something that said that the queue is reasonably threadsafe (assuming only two actors push/pop on opposing sides of the queue) back when I removed the lockqueue. I'll reintroduce the locks for now (not the old lockqueue, since I'm pretty sure now that that didn't do anything of use), but I'll probably redo the threading stuff in the future anyways.

**Comment by Meachamp** [comment]
You might be right that it won't break often, but it's still not something you should do. It just isn't something you want to risk. Your previous locking implementation actually looks mostly fine to me. I'm running a local build with it right now, and after fixing a few other things, it's working pretty well.

**Comment by timschumi** [comment]
> Your previous locking implementation actually looks mostly fine to me.

The only thing (as far as I can tell) that it took care of was ensuring that the popped item and the returned item are the same. As well as making sure that no two queue functions can run at the same time, obviously. However, it did not do anything for between function calls (for example isEmpty() and pop()), since the mutex was always limited to a single function. Therefore, I'll probably switch to "seperate" locks/mutexes, so that I can appropriately lock accross those function calls.

Well, at least until I redo the whole multithreaded thing, after which I'll hopefully have proper locking and notifying.

> I'm running a local build with it right now, and after fixing a few other things, it's working pretty well.

Now I'm curious. Have you actually experienced any issues related to race conditions or thread-safety?

**Comment by Meachamp** [comment]
Yeah, you're right about isEmpty() and pop(). In this case since it's single producer single consumer you can leave that one be, but for a general case implementation yeah you'd need a different locking strategy. 

As to what issues I found, here's what I have:
- Memory leak on error in HTTP queue call
- Reference leak with fail/success handlers
- Crash with pending HTTP calls on windows (due to thread not being stopped). The same thing would happen on linux if the module was truly unloaded. 
- Improper cleanup on linux, essentially queue state will persist across map change due to gmod modules not being unloaded. 
- "almost" memory leak on windows, since the module got unloaded but pending HTTPRequest objects weren't freed. You got saved by the fact that each module has its own heap. 

The thread management is really tricky stuff, and I'm even not sure I got it all done correctly.

**Comment by timschumi** [comment]
Awesome, thanks for the information! I'll see if I can take care of any of those.

I just pushed some changes to master, one of which was the switch to C++ threads. That change hopefully should have eliminated the never-freed thread handles (since they are now immediately detached and then deallocated). The other issues still remain though.

I also changed some stuff so that I (hopefully) deallocate the HTTPResponse struct properly now, but freeing the success/fail handlers still remains. I originally tried to fix that as well, but noticed pretty fast that I am discarding the references to at one of them at a point where I can't actually free those properly. I can hopefully take care of those design issues during the rewrite, as already mentioned below.

I also just remembered why I deprecated my implementation of the LockQueue: No matter what I did, I couldn't get GCC to statically link threading support (or at least, it didn't recognize mutexes), so I just ended up removing it as a whole. At that point, making it easier (or even _possible_ for some users) to install the library was more important to me than taking care of the off-chance that we run into a race-condition in a SPSC queue.

If you have any fixes that you feel comfortable to upstream, I'd appreciate if you do so. However (just as a heads up), I'll probably start rewriting quite a few parts (general cleanup and reorganization, making data structures and other things more C++-like, actually attaching functions to whatever data structure or class they are working on, etc.) of the library once my exams are over in a few weeks. After all, the library (as it is right now) is still very similiar to the proof-of-concept quality that it originally had.

**Comment by Meachamp** [comment]
Strangely, with your build commands I had no issues compiling and using threads. I did need to add a mutex support header since mingw doesn't support them for win32, but that was no big deal. You shouldn't need to statically link in the first place, since the libraries that you will be using will always be present on the OS.

**Comment by timschumi** [comment]
> Strangely, with your build commands I had no issues compiling and using threads.

Threads themselves are fine for whatever reason. It's just that MinGW is limited to the pthread implementation whenever you use C++11 threads. If you are only using threads, linking winpthread statically works fine (this is basically the state that the master branch is in right now).

It starts to break when using mutexes, since it can't find some symbols it needs. I still have to find out why though.

> You shouldn't need to statically link in the first place, since the libraries that you will be using will always be present on the OS.

No they aren't. MinGW tends to pull in libgcc, libstdc++, and sometimes even winpthreads, all of which aren't present on a normal Windows machine and therefore would have to be included as a dependency.

**Comment by Meachamp** [comment]
>No they aren't. MinGW tends to pull in libgcc, libstdc++, and sometimes even winpthreads, all of which aren't present on a normal Windows machine and therefore would have to be included as a dependency.
Correct for the first two, incorrect (partially) for the last one. This behavior will have changed now that you're using std threading, however previously you were using winAPI calls to handle threading on windows. 

What I'm referring to is this:
>I also just remembered why I deprecated my implementation of the LockQueue: No matter what I did, I couldn't get GCC to statically link threading support (or at least, it didn't recognize mutexes), so I just ended up removing it as a whole.

The issue was probably that std::mutex isn't supported by MinGW. It's nothing related to statically linking threads or anything like that. As I stated, threading before your recent commits was perfectly fine.

**Comment by timschumi** [comment]
> The issue was probably that std::mutex isn't supported by MinGW. It's nothing related to statically linking threads or anything like that. As I stated, threading before your recent commits was perfectly fine.

`std::mutex` is supported by MinGW, it works just fine when linking dynamically (which will pull in the winpthread library directly, due to libstdc++ not including wrappers for those symbols). However, when trying to link winpthread statically, it can't find those symbols anymore. Though I think I remember it trying to search for `_imp__*` symbols, which would imply that it is still searching for dynamically linked functions.

As a follow up, I checked on what is actually linked when I omit the `-static` linker flag (while using the posix threading API). Additionally, `libstdc++-6.dll` and `libgcc_s_sjlj-1.dll` are now linked dynamically. Also, from what I can tell in the winedump output, it's actually libstdc++ that provides the `std::thread`-related functions (and in turn pulls in `libwinpthread-1.dll`, which I assume happens as well when linking statically).

Anyways, I'll probably stop making changes for now, at least until exams are over and I took a look at your changes. Else, we'll end up invalidating each others patchsets over and over.

**Comment by timschumi** [comment]
Well fuck me, I just found the problem.

The Garry's Mod Lua API headers define `DLL_EXPORT` to [handle what the calling convention for its functions are](https://github.com/Facepunch/gmod-module-base/blob/b263361045aaef440e2eabd21f891f3920495b43/include/GarrysMod/Lua/Interface.h#L35). This taints the global state and makes pthread.h believe that its in dynamic linking mode, and therefore adds all the `_imp__` crap around everything (since it uses that definition to decide whether it should apply any modifiers).

Rearranging imports so that threads/mutexes are included before the GMod `Interface.h` file (or better, seperating them completely) fixes the linking issues and the library seems to be able to use mutexes now, even if statically linked and cross-compiled for Windows.

**Comment by Meachamp** [comment]
Amazing. I guess whatever I had was different then. When I've got some free time today, I'll take a look at getting your vagrant setup replicated and doing a full build.

**Comment by timschumi** [comment]
> Amazing. I guess whatever I had was different then. When I've got some free time today, I'll take a look at getting your vagrant setup replicated and doing a full build.

Unless you are using libvirt, you'll probably have to find a replacement for the generic-x32/debian9 box. Other than that, it should suffice if you run the `dist.sh` script and it should set up everything by itself (after all, that's the point of having everything in Vagrant boxes).

**Comment by timschumi** [comment]
@Meachamp I now uploaded all my accumulated changes, together with a set of binaries including those changes. The problem with threads not stopping during unload I should have taken care of, as well as locking and waiting until elements are available (instead of spamming new threads).

For clearing the queue I'll have to take a look later, at the moment it just joins the thread and finishes processing all the remaining requests (which I honestly prefer over just discarding them, since something might still expect those requests to be processed during shutdown).

**Comment by Meachamp** [comment]
Awesome awesome. That approach honestly seems fine for now, I'll check it out when I've got a chance.

**Comment by timschumi** [comment]
@Meachamp Have you ever gotten around to looking at the changes that I made? If so, is there anything that remains that should be taken care of?

**Comment by Meachamp** [comment]
I think I did take a look a few months ago, and it seemed much better. It's been a while so I can't remember if there were any issues, but probably nothing major. It's fine to close this issue.

**Comment by timschumi** [comment]
Alright. Again, thank you very much for looking into this!
