### ISSUE TITLE
Missing librairies

### ISSUE THREAD

**Issue by MisterWeizer** [timschumi/gmod-chttp#15]
I got that in my console after adding gmsv_chttp to link my discord to bLogs.

[GmodAdminSuite] [WARN] [bLogs] Could not load gmsv_chttp!
[GmodAdminSuite] [WARN] [bLogs] There are some missing libraries from your server's operating system.
[GmodAdminSuite] [WARN] [bLogs] This is not the fault of bLogs!!

I'm using Linux x64 on a VPS Ubuntu 10

**Comment by timschumi** [comment]
Are you sure that you are using Ubuntu 10? Because that's almost 10 years old.

Since you say that it's a VPS, I assume you have access to a shell. Could you get the output of `cat /etc/lsb-release`, as well as `ldd /path/to/the/chttp.dll`?

Also, it might be worth it to try the binaries that are located [here](https://github.com/timschumi/gmod-chttp/files/5144562/chttp-1.4.0-rc1-centos7.zip), which have been compiled against an older target system.

**Comment by MisterWeizer** [comment]
Oh yeah, sorry, ubuntu 20. Make more sense.

For the Cat /etc/ : 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

For the LDD :
ldd: home/container/garrysmod/lua/bin/gmsv_chttp.dll: No such file or directory

**Comment by timschumi** [comment]
Ah, yes, Ubuntu 20 does make more sense. In that case, the dependencies probably aren't the issue, because the OS is new enough.

Regarding the file path, that doesn't seem to be correct. The naming for the DLL usually is `gmsv_chttp_<arch>.dll`, where `arch` is one of the following: `linux`, `linux64`, `win32` or `win64`.

Can you run and post the output of `ls -al /home/container/garrysmod/lua/bin/` to figure out which library you have installed and then run ldd on that?

**Comment by MisterWeizer** [comment]
I've renamed the DLL

And for ls :

ls: cannot access 'home/container/garrysmod/lua/bin/': No such file or directory

**Comment by timschumi** [comment]
> I've renamed the DLL

Renaming the DLL will break it, the game expects the filename to be `gmsv_chttp_linux.dll` (or whatever your arch is), nothing else.

> ls: cannot access 'home/container/garrysmod/lua/bin/': No such file or directory

Are you sure that you are in the correct directory and the folder actually exists? Note the leading slash, indicating an absolute path.

**Comment by MisterWeizer** [comment]
When I sais that I’ve renamed it I was talking about the « linux64 ». 

I’m pretty sure that it is the way to the lua bin. I had to create the file so it is empty except for the gmsv_chttp_linux64.dll

If I’ve removed the slash, it was because it did the same error in the console

**Comment by timschumi** [comment]
> When I sais that I’ve renamed it I was talking about the « linux64 ».

You can't. It wants exactly one of those four names, depending on which server you are running:

- `gmsv_chttp_linux.dll` (Linux, 32-bit)
- `gmsv_chttp_linux64.dll` (Linux, 64-bit)
- `gmsv_chttp_win32.dll` (Windows, 32-bit)
- `gmsv_chttp_win64.dll` (Windows, 64-bit)

Keep in mind that unless you have manually opted into the x64 beta server, you will have to use the file for 32-bit Linux.

> I’m pretty sure that it is the way to the lua bin. I had to create the file so it is empty except for the gmsv_chttp_linux64.dll
>
> If I’ve removed the slash, it was because it did the same error in the console

Then figure out where your `lua/bin/` directory really is and then print that.

**Comment by timschumi** [comment]
I have now released [Version 1.4.1](https://github.com/timschumi/gmod-chttp/releases/tag/v1.4.1), which should be compatible with more Linux distributions and provides additional builds with even less dependencies.

Please follow the reworked [Installation instructions](https://github.com/timschumi/gmod-chttp#installation) and test whether the new version (or its `-static` variation) solves your issue. In case the issue is still present, feel free to reopen this issue report.
