### ISSUE TITLE
Control source IP for request?

### ISSUE THREAD

**Issue by swampservers** [timschumi/gmod-chttp#16]
This would be helpful to deal with ddos protection making HTTP requests not work on the game IP

**Comment by timschumi** [comment]
I'm afraid you'll have to elaborate a bit more on that.

**Comment by swampservers** [comment]
Like this: https://stackoverflow.com/questions/43398957/how-to-specify-the-ip-address-on-curl

It seems to be a common issue with GMC that HTTP requests fail because of their DDOS protection; if we could use the other interfaces on the server that would be a nice workaround.

**Comment by timschumi** [comment]
I'll consider it, but I don't feel like this is something that should be fixed (or even handled) on the side of chttp.

If your DDOS protection blocks outgoing HTTP requests, that seems like a misconfiguration of the DDOS protection to me. If it is really intended like that, then fix the routes so that the server won't choose the DDOS-protected IP for outgoing requests by default.

In any case, this is way too environment-specific to "fix" in plugin Lua code.

**Comment by swampservers** [comment]
> then fix the routes so that the server won't choose the DDOS-protected IP for outgoing requests by default.
What do you mean, iptables?

Controlling the source interface a pretty common feature; you can do it with PHP's curl too for example. One thing it's useful for more generally is getting around rate limits on a single IP.

**Comment by timschumi** [comment]
> What do you mean, iptables?

This is probably more of a job for `ip route`, at least as far as I know (although you can probably do _some_ routing magic using iptables).

If you run `ip route`, you should be able to see various routes for all of your IP addresses and at least one `default via xxx.xxx.xxx.xxx` route for where your packets are supposed to go through by default. All of the active routes also have a `metric xxx` value, where `xxx` is a number that determines the "priority" (the lower number having the higher priority).

At the moment, the default route with the lowest metric is probably the one that is attached to your game server IP (which is why your outgoing requests are being sent through that interface by default).

> Controlling the source interface a pretty common feature; you can do it with PHP's curl too for example. One thing it's useful for more generally is getting around rate limits on a single IP.

The main reason why PHP's curl has the ability to set the interface is because PHP's curl module replicates the libcurl API, and setting the interface is part of that.

On the other hand, chttp isn't a replication of the libcurl API, but rather it's a high-level abstraction so that you can easily make HTTP requests (with less restrictions than the builtin HTTP). Plugins should not have to care about the interface that your requests go through, and they probably shouldn't have the ability to affect routing either.

The only option that I would consider is setting the interface once globally and never exposing that ability to the Lua API, but I still believe that this should be handled by the OS and its network interface settings, which do a way better job at routing. Also, I don't have any ideas on how I should actually implement that.

**Comment by swampservers** [comment]
I see, I was thinking it would be a new argument in https://wiki.facepunch.com/gmod/Structures/HTTPRequest (which the stock HTTP should just ignore). Thank you for the routing tips!

**Comment by timschumi** [comment]
Implemented in commit abe3c9de54a7476c5a44ac596668f6ffa57df09c and released in [v1.4.2](https://github.com/timschumi/gmod-chttp/releases/tag/v1.4.2).

Due to security concerns, this has been implemented as an environment variable instead (please make sure to read [its documentation](https://github.com/timschumi/gmod-chttp/tree/v1.4.2#source-interface)).
