### ISSUE TITLE
Not working on ubuntu server 18.04

### ISSUE THREAD

**Issue by CoolGoga** [timschumi/gmod-chttp#2]
Hello! I have a problem with using your module on ubuntu server. Check this picture:
![изображение](https://user-images.githubusercontent.com/19359697/68472489-1280a180-023a-11ea-8a27-9d77866f391a.png)

**Comment by timschumi** [comment]
The "Couldn't load module library" error is usually caused by GMod not finding the dependency libraries.

Please make sure that curl (and libcurl if it's a seperate package) is installed.

If it still doesn't work after that, please run `ldd /path/to/gmsv_chttp_linux.dll` and post the output here (in a code block, please). It will show if and what libraries have been resolved and which haven't.

**Comment by CoolGoga** [comment]
Yes, i installed libcurl and curl packages but it does not work

ldd output:

`	linux-gate.so.1 (0xf7f56000)
	libcurl.so.4 => not found
	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7db5000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7cb3000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7c95000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7ab9000)
	/lib/ld-linux.so.2 (0xf7f58000)
`

it says that libcurl.so.4 not found but i have this file (/usr/lib/x86_64-linux-gnu/libcurl.so.4)

**Comment by timschumi** [comment]
The library is a 32-bit addon, it needs the 32-bit libcurl to work properly (as indicated by the `i386-linux-gnu` output of the resolved libraries instead of `x86_64-linux-gnu`).

To install those on Ubuntu, you'll have to go through a few extra steps, as outlined here: https://askubuntu.com/questions/1007533/how-to-install-32-bit-libcurl-on-64-bit-ubuntu-16
However, you will probably want to install the `libcurl4:i386` package instead of `libcurl4-openssl-dev:i386` (I'm not sure whether the latter even exists anymore).

**Comment by CoolGoga** [comment]
Thanks! Now it works!

**Comment by timschumi** [comment]
I added a note about libcurl having to be 32-bit to the installation steps, so that it is more clear in the future.

And a little bit of OT since you are one of the first users (if not _the_ first) and I'm too curious to not ask: How did you find this?

**Comment by CoolGoga** [comment]
Just looking for random repos related to gmod =) Then i realized that this binary module can be useful! We use it to spoof User-Agent header (for discord api/webhook) cause the standard library prohibits this)

**Comment by timschumi** [comment]
Funnily enough, that is exactly the reason that I wrote it for, in conjunction with a direct-interface Discord bot.
